# Generated by Django 6.1 on 2026-08-14 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Chapter",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("volume", models.PositiveIntegerField()),
                ("chapter", models.PositiveIntegerField()),
                ("index", models.PositiveIntegerField()),
                ("title", models.CharField(max_length=200)),
                ("slug", models.SlugField(max_length=200, unique=True)),
                ("content", models.TextField()),
                ("symbols", models.PositiveIntegerField()),
                ("date", models.DateField()),
            ],
        ),
    ]
