# Generated by Django 6.1 on 2026-08-17 07:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chapters", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="chapter",
            name="date",
        ),
        migrations.RemoveField(
            model_name="chapter",
            name="index",
        ),
        migrations.AddField(
            model_name="chapter",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True,
                default="2026-08-17T07:22:00",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="chapter",
            name="updated_at",
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="chapter",
            field=models.DecimalField(),
        ),
        migrations.AlterField(
            model_name="chapter",
            name="id",
            field=models.PositiveIntegerField(primary_key=True, serialize=False),
        ),
    ]
