# Generated by Django 6.1 on 2026-08-17 07:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("chapters", "0002_remove_chapter_date_remove_chapter_index_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="chapter",
            name="chapter",
            field=models.DecimalField(decimal_places=1, max_digits=5),
        ),
    ]
